source 'https://github.com/CocoaPods/Specs.git'

target 'FSMediaPicker', :exclusive => true do
  pod "FSMediaPicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FSMediaPicker", :path => "../"

  
end
